FROM apache/hadoop:3

USER root

RUN sed -i 's|mirrorlist=|#mirrorlist=|g' /etc/yum.repos.d/CentOS-* && \
    sed -i 's|#baseurl=http://mirror.centos.org|baseurl=http://vault.centos.org|g' /etc/yum.repos.d/CentOS-*

RUN yum -y update && \
    yum -y install python3 python3-pip && \
    yum clean all

RUN python3 --version && pip3 --version

USER hadoop